### ISSUE TITLE
Uploading Data to Compass 

### ISSUE THREAD

**Issue by jenniferghu** [rpasquini/twitter_and_displacement#6]
Currently running the "Start Here Procedure Guide notebook" on Jupyter, but my databasepopulation.py file is erroring at "from h3 import h3". Everything on my Jupyter is synced to what is on the repository, so I am unsure where this error is coming from.

**Comment by jenniferghu** [comment]
Nevermind, re-started my notebook and it ran this time!

**Comment by jenniferghu** [comment]
While trying to upload the raw data to Compass, I keep on getting a time out error. Emmanuel and I originally thought that this might be because we were uploading data at the same time, but that does not seem to be the issue. The error states:
`3.14.72.122:27017: timed out, Timeout: 30s, Topology Description: <TopologyDescription id: 5f84a39db120853744c0bbaf, topology_type: Single, servers: [<ServerDescription ('3.14.72.122', 27017) server_type: Unknown, rtt: None, error=NetworkTimeout('3.14.72.122:27017: timed out')>]>`

**Comment by rpasquini** [comment]
I can see that uploading Sydney seemed to went well. Did this error appeared just now or appears from time to time? Does the problem disappear after retrying or it is not letting you insert any document at all?

**Comment by Emman-Lopez-Oso** [comment]
@rpasquini , I was the one who uploaded Sydney and made the instructions via video on how to interact with the notebooks. For some reason, Jen was not able to upload the data for Bogota on her end.

**Comment by rpasquini** [comment]
@Emman-Lopez-Oso  did you have any time out errors in uploading the raw data?

**Comment by Emman-Lopez-Oso** [comment]
I did not.

**Comment by rpasquini** [comment]
@jenniferghu Are you sure you have connected correctly to Mongo server? Could you insert a document to the server at least once?

**Comment by rpasquini** [comment]
@jenniferghu  I've sent some code to test via slack chat

**Comment by jenniferghu** [comment]
Getting the error "k_ring_distances() got an unexpected keyword argument 'ring_size'" on section 7. Everything is running fine until then, and I have re-ran the code, but am still getting the error.

**Comment by Emman-Lopez-Oso** [comment]
So I'm looking at the analysis.py file right now, and when I go to the function neighboring_hex_list() it doesn't appear to the ring_size parameter attached to it. @jenniferghu , can you open up analysis.py in some text editor and tell me what the parameters look like for the function `neighboring_hex_list()` Ours should not be different but they may be.

**Comment by jenniferghu** [comment]
This is what I see from my end:
`def users_in_hex_plus_neighbors_list(db, hexid, contiguity=1, resolution='9'):
    """Adding neigbors of specified contiguity using h3 ring functions

    # comment> Shouldnt be necessary to specify resolution once hexid is given> check h3 documentation to obtain resoltuion on the basis of hexid
    """

    neighboring_hex_list = list(h3.k_ring_distances(hexid, ring_size=contiguity)[contiguity])

    # funcion para graficar los poligonos
    # gdf=hexlist_to_geodataframe(neighboring_hex_list)
    # gdf.plot()

    users_in_hex_plus_neighbors_list = []

    users_in_hex_list2 = users_in_hex_list(db, hexid, resolution=resolution)

    users_in_hex_plus_neighbors_list.extend(users_in_hex_list2)  # adding first those living in hex

    hexfieldname_indb = 'hex' + resolution + "." + 'hex' + resolution

    for n_hexid in neighboring_hex_list:

        users_in_n_hex_cursor = db.users.find({hexfieldname_indb: n_hexid})
        users_in_n_hex_df = pd.DataFrame(list(users_in_n_hex_cursor))

        try:
            users_in_n_hex_list = list(users_in_n_hex_df['u_id'])
        except KeyError:
            pass
        else:
            users_in_hex_plus_neighbors_list.extend(users_in_n_hex_list)
    return users_in_hex_plus_neighbors_list`

**Comment by Emman-Lopez-Oso** [comment]
Thanks, Jen. Yeah, so that `ring_size=` parameter has been deprecated and leads to the function not working. You can delete it and the function will work. @rpasquini, I made a pull request because my fork is quite a bit different from yours. 

I think that maybe @jenniferghu is working from your repository when my forked repository has a series of changes (including the observation area specific folders). I made a pull request to bring in the changes that I've made in my repository into this one.

**Comment by rpasquini** [comment]
Hi everybody, 
As @Emman-Lopez-Oso points out, this is an h3 related version problem.
@jenniferghu we talked about of working in a conda environment using the project's version specifications. Are you actually running the notebook in such an environment? Did you see my messages in slack on how to activate and select the proper environment within Jupyter? Please let me know if there are any related doubts.
I would prefer you to run the notebook in such a tested environment in order to avoid similar problems.
@Emman-Lopez-Oso thanks for this. I will not integrate the complete pull request since it has conflicts and would break the master project. I will use the pull request to track your changes in the main functions that are related to new versions. I will have to test them before incorporating such changes. As soon as I do that I will let you know and change the installation requirements in the readme file.
I also saw that you pulled cities specific notebooks. That shouldn't be a problem to integrate. I will check if I can integrate them individually or ask you to generate a new commit only including the notebooks.

**Comment by jenniferghu** [comment]
@rpasquini Yes, I am currently working in a conda environment that should be using the drafted environment file. I am running the command "jupyter notebook" to make sure that my jupyter notebook is running locally, and everything has worked until this section. I am trying to re-run section 7 using Emmanuel's suggestions. The notebook has been running for a few hours already since I needed to start from the beginning, but I will update you all to see if that fixes the problem. Thanks!

**Comment by rpasquini** [comment]
@jenniferghu OK! 
A few points to note:

As I recall you only need to remove the "ring_size=" from the function, since in new versions the parameter is now positional (should recognize it without the name). No more deleting than this.

You can check the h3 version you are using  by running: 
` h3.versions()
`
In order to run the notebook in your conda created environment remember to activate the environment first,
` conda activate twitteranalysis
`
and to create the ipykernel, for instance by using:

`python -m ipykernel install --user --name twitteranalysis --display-name "Python (twitteranalysis)"
`
After you start the notebook with 
`jupyter notebook
`
You should be able to select the "Python (twitteranalysis)" from the dropdown menu in the upper right corner.

**Comment by jenniferghu** [comment]
I just got to section 7, and am now getting the error `k_ring_distances() missing 1 required positional argument: 'K'`. I deleted the ring_size argument, so the code now states `neighboring_hex_list = list(h3.k_ring_distances(hexid)[contiguity])`. Additionally, this is what I get when I call h3.versions "{'c': '3.7.0', 'python': '3.7.0'}". Does this seem correct? @rpasquini

**Comment by rpasquini** [comment]
No, I am afraid it does not. Your notebook is not running in the conda environment. Either because it wasn't activated or the ipykernel is missing. 
I suggest you reload the notebook by following the instructions above. If you have any problems, drop me a message and I can connect via Zoom.
 
The quick fix up for the current bug seems to be in the line you changed. Try with this:

`neighboring_hex_list = list(h3.k_ring_distances(hexid, contiguity)[contiguity])`

**Comment by jenniferghu** [comment]
@rpasquini @Emman-Lopez-Oso changing the line did not fix the error, however, it seems like all the data for bogota(2012) was uploaded in a format that matches Emmanuel's format. is section 7 and onwards needed or should I continue to try to just upload data?
