### ISSUE TITLE
Econometrics by typologies - Bogota: Bug

### ISSUE THREAD

**Issue by Emman-Lopez-Oso** [rpasquini/twitter_and_displacement#8]
# **Location**: 

### Step 1. Obtain the hex counts data and turn the geometry into centroids
```
# Get counts at hex level from the database 
df=a.hexcountsresults_to_df(db, save=False)
```

# **Output**:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-9-5b4cff4e0197> in <module>
      1 # Get counts at hex level from the database
----> 2 df=a.hexcountsresults_to_df(db, save=False)

~\Documents\git\twitter_and_displacement\py_func_NoEnvReq\analysis.py in hexcountsresults_to_df(db, save)
    913     prueba=pd.DataFrame(list(cursor) )
    914 
--> 915     df1=pd.DataFrame(pd.concat([prueba[['_id']],pd.json_normalize(prueba["nonresidents"])],axis=1 ).set_index('_id').stack()).reset_index().rename(columns={0:'nonresidents'})
    916     df2=pd.DataFrame(pd.concat([prueba[['_id']],pd.json_normalize(prueba["nonresidentsandnonneighbors"])],axis=1 ).set_index('_id').stack()).reset_index().rename(columns={0:'nonresidentsandnonneighbors'})
    917     df3=pd.DataFrame(pd.concat([prueba[['_id']],pd.json_normalize(prueba["residents"])],axis=1 ).set_index('_id').stack()).reset_index().rename(columns={0:'residents'})

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\json\_normalize.py in _json_normalize(data, record_path, meta, meta_prefix, record_prefix, errors, sep, max_level)
    276             # TODO: handle record value which are lists, at least error
    277             #       reasonably
--> 278             data = nested_to_record(data, sep=sep, max_level=max_level)
    279         return DataFrame(data)
    280     elif not isinstance(record_path, list):

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\io\json\_normalize.py in nested_to_record(ds, prefix, sep, level, max_level)
     80     for d in ds:
     81         new_d = copy.deepcopy(d)
---> 82         for k, v in d.items():
     83             # each key gets renamed with prefix
     84             if not isinstance(k, str):

AttributeError: 'float' object has no attribute 'items'
```

# **Assumption**: 

Raw Bogota data at the Tweet level was either uploaded erroneously or the data had some characters that, when imported, caused an improper interpretation for the data during the transfer and leads to the reading into a dataframe to break. 

# **Next Steps:**

Go into the Bogota data and figure out what the data type is and what might be causing this to occur.

**Comment by rpasquini** [comment]
I've been looking to the data, and the problem seems to be that Step 7 (Count tweets in each hex by residents and non-residents) did not complete.  As you can see in the following, the bottom of the collection is empty. 
 
![image](https://user-images.githubusercontent.com/7108317/98039876-2aafe000-1dfe-11eb-87c8-56511ac1115d.png)


The solution should be as simple as repeat step 7 until all the collection is processed.  It is not necessary to delete the existent hexcounts collection, since by invoking `a.countandpopulatejob(db)` the process should start with the job that is pending. 

It should give a message when finishes. Something like "fin", as shown below for Buenos Aires:
![image](https://user-images.githubusercontent.com/7108317/98040206-a742be80-1dfe-11eb-9106-9fb44b877f87.png)
